#!/usr/bin/env bash
# A script to ping an IP address provided as an argument

# IP address variable
IP="${1}"

# Filename variable
filename=$(basename "${BASH_SOURCE[@]}")

# Checking if IP address is provided
if ! [ "$IP" ]; then
	echo "Usage: ${filename} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi

