#!/usr/bin/env bash

# Check if the script is running with superuser privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root"
    exit 1
fi

# Change localhost IP to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Change facebook.com IP to 8.8.8.8
sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/8.8.8.8/' /etc/hosts

echo "IPs changed successfully"

